### ISSUE TITLE
Recovery old issues?

### ISSUE THREAD

**Issue by shadowspawn** [minimistjs/minimist#63]
Inspired by some issues "recovered" in [subarg](https://github.com/minimistjs/subarg/issues) I went looking for Minimist issues.

Shall I "recover" these?
https://web.archive.org/web/20210211062650/https://github.com/substack/minimist/issues

Mostly OLD issues, but some covering things we have addressed, like documenting `--no-*` behaviour.

**Comment by ljharb** [comment]
The reason it worked for subarg is that there were only 8 issues/PRs, so i could keep the numbers the same, and, it was a manageable number.

If there are a small number of issues that are worth migrating, perhaps it’s worth recreating those issues, but otherwise maybe just adding a link to the archive.org URL for the old repo?

**Comment by shadowspawn** [comment]
Yes I was thinking of a subset, I'll have a more careful look through for whether worthwhile.

**Comment by shadowspawn** [comment]
Created new issues from two, and added historical references for issues that have been resolved in this repo.
